CREATE TABLE IF NOT EXISTS cfb.games (
    id                            INT,
    season                        INT,
    week                          INT,
    season_type                   VARCHAR(10),
    start_date                    DATE,
    start_time_tbd                BOOLEAN,
    completed                     BOOLEAN,
    neutral_site                  BOOLEAN,
    conference_game               BOOLEAN,
    attendance                    INT,
    venue_id                      INT,
    venue                         VARCHAR(50),
    home_id                       INT,
    home_team                     VARCHAR(25),
    home_conference               VARCHAR(50),
    home_classification           VARCHAR(50),
    home_points                   INT,
    home_line_scores              INT[],
    home_postgame_win_probability DECIMAL(8, 8),
    home_pregame_elo              INT,
    home_postgame_elo             INT,
    away_id                       INT,
    away_team                     VARCHAR(25),
    away_conference               VARCHAR(50),
    away_classification           VARCHAR(50),
    away_points                   INT,
    away_line_scores              INT[],
    away_postgame_win_probability DECIMAL(8, 8),
    excitement_index              DECIMAL(12, 8),
    highlights                    TEXT,
    away_pregame_elo              INT,
    away_postgame_elo             INT,
    notes                         TEXT
);
