CREATE TABLE IF NOT EXISTS basketball.stat_sheet (
    player VARCHAR(255) NOT NULL,
    minutes_played INTERVAL,
    field_goals INT NOT NULL,
    field_goals_attempted INT NOT NULL,
    field_goal_percentage DECIMAL(5,3) NOT NULL,
    three_pointers INT NOT NULL,
    three_pointers_attempted INT NOT NULL,
    three_pointer_percentage DECIMAL(5,3) NOT NULL,
    free_throws INT NOT NULL,
    free_throws_attempted INT NOT NULL,
    free_throw_percentage DECIMAL(5,3) NOT NULL,
    offensive_rebounds INT NOT NULL,
    defensive_rebounds INT NOT NULL,
    total_rebounds INT NOT NULL,
    assists INT NOT NULL,
    steals INT NOT NULL,
    blocks INT NOT NULL,
    turnovers INT NOT NULL,
    personal_fouls INT NOT NULL,
    points INT NOT NULL,
    plus_minus INT NOT NULL,
    team VARCHAR(3) NOT NULL,
    opponent VARCHAR(3) NOT NULL,
    visitor VARCHAR(3) NOT NULL,
    home VARCHAR(3) NOT NULL,
    date DATE,
    player_id VARCHAR(32) NOT NULL,
    game_id VARCHAR(32) NOT NULL,
    FOREIGN KEY (player_id) REFERENCES basketball.player_id(unique_id),
    FOREIGN KEY (game_id) REFERENCES basketball.all_games(unique_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_player_team_date UNIQUE (player, team, date)
);